/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(accelerometer.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(3a4dd340086c532d9d6e7e0d3f913e37)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/grand/accelerometer.h>
// pydoc.h is automatically generated in the build directory
#include <accelerometer_pydoc.h>

void bind_accelerometer(py::module& m)
{

    using accelerometer    = gr::grand::accelerometer;


    py::class_<accelerometer,
        gr::sync_block,
        gr::block,
        gr::basic_block,
        PYBIND11_SH_DEF(accelerometer)>(m, "accelerometer", D(accelerometer))

        .def(py::init(&accelerometer::make),
           D(accelerometer,make)
        )
        



        ;




}








