/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(float_array.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(06eec9ceff81504b6ddd96d658284761)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/grand/float_array.h>
// pydoc.h is automatically generated in the build directory
#include <float_array_pydoc.h>

void bind_float_array(py::module& m)
{

    using float_array    = gr::grand::float_array;


    py::class_<float_array,
    gr::sync_block,
        gr::block,
        gr::basic_block,
        PYBIND11_SH_DEF(float_array)>(m, "float_array", D(float_array))

        .def(py::init(&float_array::make),
           py::arg("array"),
           py::arg("len"),
           py::arg("*vm"),
           D(float_array,make)
        )
        



        ;




}








