/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(light_sensor.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(ee143cd31a8338579e1c98a1ff3e84af)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/grand/light_sensor.h>
// pydoc.h is automatically generated in the build directory
#include <light_sensor_pydoc.h>

void bind_light_sensor(py::module& m)
{

    using light_sensor    = gr::grand::light_sensor;


    py::class_<light_sensor,
    gr::sync_block,
        gr::block,
        gr::basic_block,
        PYBIND11_SH_DEF(light_sensor)>(m, "light_sensor", D(light_sensor))

        .def(py::init(&light_sensor::make),
           D(light_sensor,make)
        )
        



        ;




}








