/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(opensl_source.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(279a624a1b5550e25b69d35563053714)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/grand/opensl_source.h>
// pydoc.h is automatically generated in the build directory
#include <opensl_source_pydoc.h>

void bind_opensl_source(py::module& m)
{

    using opensl_source    = gr::grand::opensl_source;


    py::class_<opensl_source,
    gr::sync_block,
        gr::block,
        gr::basic_block,
        PYBIND11_SH_DEF(opensl_source)>(m, "opensl_source", D(opensl_source))

        .def(py::init(&opensl_source::make),
           py::arg("sampling_rate"),
           D(opensl_source,make)
        )
        



        ;




}








